### ISSUE TITLE
Input for prediction

### ISSUE THREAD

**Issue by RuiLoureiro** [frederic-bousefsaf/ippg-3dcnn#1]
First of all, thank you for making the code for this very interesting paper publicly available.
I'm trying to run predictions and was expecting the input to be a video, but it seems to be a folder with images. Why is that?

**Comment by frederic-bousefsaf** [comment]
Thanks for your message. The input is indeed a sequence of images. A video is in fact the exact same thing (a sequence of images) except that the representation is different (all images are included in a single file). You can easily adapt the program by replacing the loading part (Line 23 to 48) with, for example, an OpenCV function (VideoCapture) that reads a video.

**Comment by RuiLoureiro** [comment]
Thank you.
